# https://just.systems/man/en/quick-start.html

# List commands
default:
  @just --list --no-aliases

docs:
    mkdocs serve

[group('test')]
test-unit:
    -pytest --no-summary --no-header -k unit

[group('test')]
test-filter NAME:
    -pytest -v --no-summary --no-header -k {{NAME}}

[group('static-check')]
format:
    black .
