class LoadError(BaseException): ...


class MergeError(BaseException): ...


class SchemaError(BaseException): ...


class DynaconfNotInitialized(BaseException): ...


class UnknownNamespace(BaseException): ...
